SCORE_LOGIT = """Here are two images: the original and the edited version. Please evaluate the edited image based on the following editing instruction and requirement. 
Instruction: {prompt}
Requirements: {requirement}
You need to rate the editing result from 0 to 5 based on the accuracy and quality of the edit. 
0: The wrong object was edited, or the edit completely fails to meet the requirements. 
5: The correct object was edited, the requirements were met, and the visual result is high quality.
Response Format (Directly response the score number): 
0-5"""

QUA_SCORE = """Your role is to evaluate the aesthetic quality score of given images.
1. Bad: Extremely blurry, underexposed with significant noise, indiscernible subjects, collapsed subjects, and chaotic composition.
2. Poor: Noticeable blur, poor lighting, washed-out colors, and awkward composition with cut-off subjects, incomplete object .
3. Fair: In focus with adequate lighting, dull colors, decent composition but lacks creativity.
4. Good: Sharp, good exposure, vibrant colors, thoughtful composition with a clear focal point.
5. Excellent: Exceptional clarity, perfect exposure, rich colors, masterful composition with emotional impact.

Respose Format (Please specify the reason for the deduction within the <Reason> tag. Respond to the score directly within the <Score> tag.):
<Reason>...</Reason><Score>1-5</Score>
"""

CON_SCORE = """Your role is to evaluate whether a specific object present in the reference image is correctly retained in the edited image. The task is not to assess global similarity, but to verify that the edited image contains the same object from Reference Image, matching in identity and essential visual characteristics.
The edited image is generted by {prompt}, It involve a object insertion or replacement.
Please only focus on the items that coexist in reference image and the edited image, ignoring other elements in the edited image.
Evaluating consistency is not pixel level, but rather from aspects such as material, shape, arrangement, color, lighting, composition, etc
1. No Match: The object from Reference Image is completely absent in Edited Image, or a different object (different category or identity) appears in its place.
2. Weak Match: An object of the same general category is present (e.g., “a chair” instead of “the red office chair”), but key identifying features (color, shape, style, brand, or distinctive markings) are missing or altered beyond recognition.
3. Partial Match: The correct object is likely intended, but critical attributes are inconsistent (e.g., wrong color, material changed, major design elements missing), making it visually distinct from the reference. Excessive structure or ghosting appears.
4. Match: The object in Edited Image closely matches the one in Reference Image  in type, form, color, texture, and distinctive details; minor differences due to lighting, viewpoint, partial occlusion, or editing artifacts are acceptable.
5. Exact Match: The object in Edited is visually faithful to the one in Reference Image across all defining characteristics—same model, condition, color, pose, and unique identifiers—with only natural variations expected from image editing (e.g., perspective shift, brightness adjustment).

Respose Format (Please specify the reason for the deduction within the <Reason> tag. Respond to the score directly within the <Score> tag.):
<Reason>...</Reason><Score>1-5</Score>
"""

SCE_SCORE = """You are evaluating scene-level consistency between a scene image and an edited image. The edit involves only a localized change (e.g., adding or replacing an object like a watch, bag, or clothing).
The Edited image is generated by {prompt}, It involve a object insertion or replacement. Ignore the edited object itself. 
Do not judge based on changed meaning or style due to the edited object.
Instead, assess whether the rest of the scene—including environment, lighting, perspective, and any human subjects (pose, anatomy, orientation)—remains physically coherent and visually unchanged.
Pay special attention to:
Human pose and body integrity (no distortions or unnatural limbs),
Background stability (no warping, ghosting, or foreign textures),
Consistent lighting, shadows, and camera perspective,
No leakage of background or style from the source of the inserted object.

Scoring Criteria (focus: unchanged scene integrity):
1. Inconsistent: The non-edited parts of the scene are fundamentally altered—e.g., indoor/outdoor switch, distorted room geometry, warped background, or human anatomy broken; clear contamination from the source object’s context.
2. Mostly Inconsistent: Scene type is recognizable, but major artifacts in unchanged areas: severe pose distortion, mismatched global lighting, perspective shift, or visible background bleed affecting realism.
3. Partially Consistent: Core structure is preserved, but subtle issues in non-edited regions—e.g., slight pose drift, inconsistent ambient occlusion, minor texture warping, or soft lighting mismatches—reduce plausibility.
4. Mostly Consistent: Unchanged content (scene + subject) remains visually stable; lighting, perspective, and materials align well. Only negligible imperfections (e.g., tiny shadow edge discrepancy) that don’t break immersion.
5. Fully Consistent: The entire non-edited portion is indistinguishable from the original—perfect preservation of pose, environment, lighting, and style. No trace of external contamination or structural alteration.

Respose Format (Please specify the reason for the deduction within the <Reason> tag. Respond to the score directly within the <Score> tag.):
<Reason>...</Reason><Score>1-5</Score>
"""

HAR_SCORE = """Your role is to evaluate the harmonization quality of a reference object (from Image 1) after it has been inserted or edited. The assessment focuses primarily on the physical and common-sense plausibility of the object within its new environment or the interaction mode between people and objects.
Pay more attention to the wearing mode (such as the screen orientation, the position), grip posture, clipping and violation of gravity.

1. Poor Harmony: The object appears obviously pasted in—sharp cut-out edges, physically impossible positions or poses, implausible scale/proportions for the setting, or semantically absurd placements. collage effect.
2. Fair Harmony: While the object could belong to the plausible category for the scene, there are noticeable issues related to physical rules or common sense, such as objects intersecting unnaturally (clipping issues), or unrealistic interactions between objects. These issues significantly detract from realism despite attempts at blending.
3. Ordinary Harmony: Objects are placed generally conform to the physical logic of the scene. However, it may violate the patterns of daily use, such as slight clipping artifacts or unrealistic object interactions (such as inappropriate wearing patterns, unreasonable orientations, etc., positions that do not conform to daily use), but these will not seriously affect the overall credibility.
4. Good Harmony: The placement and interaction of the object closely follow physical laws and common usage patterns, with only minute flaws that might escape notice by most viewers. Aspects like lighting direction, shadow softness, and color grading are also well-matched. Only expert scrutiny might reveal editing traces.
5. Excellent Harmony: The inserted object is indistinguishable from native scene content, perfectly aligned with physical rules, daily use patterns, and visual consistency. There are no visual cues suggesting compositing—it reads as a single, authentic photograph.

Respose Format (Please specify the reason for the deduction within the <Reason> tag. Respond to the score directly within the <Score> tag.):
<Reason>...</Reason><Score>1-5</Score>
"""

PRO_SCORE = """
Your role is to evaluate how faithfully and effectively an editing instruction has been executed when inserting or modifying reference images. The primary focus is on instruction adherence: whether the requested change was carried out accurately.

You will receive Three images, only the last image is the edited image.
Image 1: Reference Image 1
Image 2: Reference Image 2
Image 3: Edited Image, your subject to evaluate.
Instruction:{prompt}
Please first identify which are reference images and which are edited images, analyze the content presented by the input images separately, and then determine whether the instructions have been followed.

1. Bad Execution: The editing instruction is largely ignored or misinterpreted. The wrong object is inserted, placed in an irrelevant location, or depicted in a way that contradicts the directive (e.g., instructed to “place a coffee cup on the table” but a teapot appears on the floor). Severe violations of physics or context further undermine fidelity.
2. Poor Execution: The general intent of the instruction is recognizable, but key details are inaccurate or incomplete—wrong orientation, incorrect scale, missing required interactions (e.g., cup floating above table instead of resting on it), or partial fulfillment (only part of a multi-step instruction is followed).
3. Fair Execution: The instruction is mostly followed correctly: the right object appears in the specified location with appropriate orientation and basic interaction. Minor deviations exist—such as slight misalignment, weak contact with supporting surfaces, or subtle inconsistencies in usage context—but the core request is fulfilled.
4. Good Execution: The instruction is executed with high precision. Object identity, position, pose, and interaction align closely with the directive. Physical contact, support, and spatial relationships appear natural. Visual blending (lighting, shadows, color) supports realism, though tiny imperfections may remain upon close inspection.
5. Excellent Execution: The instruction is implemented flawlessly. Every aspect—object type, placement, orientation, physical interaction (e.g., proper support, no clipping), and semantic context—matches the directive exactly. The result looks like a native part of the original photograph, with no detectable errors in logic, physics, or execution.

Respose Format (Please specify the reason for the deduction within the <Reason> tag. Respond to the score directly within the <Score> tag.):
<Reason>...</Reason><Score>1-5</Score>
"""
task_1 = '''evaluate the aesthetic quality score of given images.
1. Bad: Extremely blurry, underexposed with significant noise, indiscernible subjects, collapsed subjects, and chaotic composition.
2. Poor: Noticeable blur, poor lighting, washed-out colors, and awkward composition with cut-off subjects, incomplete object .
3. Fair: In focus with adequate lighting, dull colors, decent composition but lacks creativity.
4. Good: Sharp, good exposure, vibrant colors, thoughtful composition with a clear focal point.
5. Excellent: Exceptional clarity, perfect exposure, rich colors, masterful composition with emotional impact.
'''
task_2 = '''evaluate whether a specific object present in the reference image (Image 1) is correctly retained in the edited image (Image 2). The task is not to assess global similarity, but to verify that the edited image contains the same object from Image 1, matching in identity and essential visual characteristics.
Please only focus on the items that coexist in reference image 1 and the edited image, ignoring other elements in the edited image.
Evaluating consistency is not pixel level, but rather from aspects such as material, shape, arrangement, color, lighting, composition, etc
1. No Match: The object from Image 1 is completely absent in Image 2, or a different object (different category or identity) appears in its place.
2. Weak Match: An object of the same general category is present (e.g., “a chair” instead of “the red office chair”), but key identifying features (color, shape, style, brand, or distinctive markings) are missing or altered beyond recognition.
3. Partial Match: The correct object is likely intended, but critical attributes are inconsistent (e.g., wrong color, material changed, major design elements missing), making it visually distinct from the reference. Excessive structure or ghosting appears.
4. Match: The object in Image 2 closely matches the one in Image 1 in type, form, color, texture, and distinctive details; minor differences due to lighting, viewpoint, partial occlusion, or editing artifacts are acceptable.
5. Exact Match: The object in Image 2 is visually faithful to the one in Image 1 across all defining characteristics—same model, condition, color, pose, and unique identifiers—with only natural variations expected from image editing (e.g., perspective shift, brightness adjustment).
'''
task_3 = '''evaluating scene-level consistency between a reference image (Image 1) and an edited image (Image 2). The edit involves only a localized change (e.g., adding or replacing an object like a watch, bag, or clothing).
Ignore the edited object itself. Do not judge based on changed meaning or style due to the edited object.
Instead, assess whether the rest of the scene—including environment, lighting, perspective, and any human subjects (pose, anatomy, orientation)—remains physically coherent and visually unchanged.
Pay special attention to:
Human pose and body integrity (no distortions or unnatural limbs),
Background stability (no warping, ghosting, or foreign textures),
Consistent lighting, shadows, and camera perspective,
No leakage of background or style from the source of the inserted object.

Scoring Criteria (focus: unchanged scene integrity):
1. Inconsistent: The non-edited parts of the scene are fundamentally altered—e.g., indoor/outdoor switch, distorted room geometry, warped background, or human anatomy broken; clear contamination from the source object’s context.
2. Mostly Inconsistent: Scene type is recognizable, but major artifacts in unchanged areas: severe pose distortion, mismatched global lighting, perspective shift, or visible background bleed affecting realism.
3. Partially Consistent: Core structure is preserved, but subtle issues in non-edited regions—e.g., slight pose drift, inconsistent ambient occlusion, minor texture warping, or soft lighting mismatches—reduce plausibility.
4. Mostly Consistent: Unchanged content (scene + subject) remains visually stable; lighting, perspective, and materials align well. Only negligible imperfections (e.g., tiny shadow edge discrepancy) that don’t break immersion.
5. Fully Consistent: The entire non-edited portion is indistinguishable from the original—perfect preservation of pose, environment, lighting, and style. No trace of external contamination or structural alteration.
'''
task_4 = '''evaluate the harmonization quality of a reference object after it has been inserted or edited into a target scene. The assessment focuses primarily on the physical and common-sense plausibility of the object within its new environment or the interaction mode between people and objects.
1. Poor Harmony: The object appears obviously pasted in—sharp cut-out edges, physically impossible positions or poses, implausible scale/proportions for the setting, or semantically absurd placements. collage effect.
2. Fair Harmony: While the object could belong to the plausible category for the scene, there are noticeable issues related to physical rules or common sense, such as objects intersecting unnaturally (clipping issues), or unrealistic interactions between objects. These issues significantly detract from realism despite attempts at blending.
3. Ordinary Harmony: Objects are placed generally conform to the physical logic of the scene. However, it may violate the patterns of daily use, such as slight clipping artifacts or unrealistic object interactions (such as inappropriate wearing patterns, unreasonable orientations, etc., positions that do not conform to daily use), but these will not seriously affect the overall credibility.
4. Good Harmony: The placement and interaction of the object closely follow physical laws and common usage patterns, with only minute flaws that might escape notice by most viewers. Aspects like lighting direction, shadow softness, and color grading are also well-matched. Only expert scrutiny might reveal editing traces.
5. Excellent Harmony: The inserted object is indistinguishable from native scene content, perfectly aligned with physical rules, daily use patterns, and visual consistency. There are no visual cues suggesting compositing—it reads as a single, authentic photograph.
'''
task_5 = '''evaluate how faithfully and effectively an editing instruction has been executed when inserting or modifying a reference object into a target scene. The primary focus is on instruction adherence: whether the requested change was carried out accurately.
1. Bad Execution: The editing instruction is largely ignored or misinterpreted. The wrong object is inserted, placed in an irrelevant location, or depicted in a way that contradicts the directive (e.g., instructed to “place a coffee cup on the table” but a teapot appears on the floor). Severe violations of physics or context further undermine fidelity.
2. Poor Execution: The general intent of the instruction is recognizable, but key details are inaccurate or incomplete—wrong orientation, incorrect scale, missing required interactions (e.g., cup floating above table instead of resting on it), or partial fulfillment (only part of a multi-step instruction is followed).
3. Fair Execution: The instruction is mostly followed correctly: the right object appears in the specified location with appropriate orientation and basic interaction. Minor deviations exist—such as slight misalignment, weak contact with supporting surfaces, or subtle inconsistencies in usage context—but the core request is fulfilled.
4. Good Execution: The instruction is executed with high precision. Object identity, position, pose, and interaction align closely with the directive. Physical contact, support, and spatial relationships appear natural. Visual blending (lighting, shadows, color) supports realism, though tiny imperfections may remain upon close inspection.
5. Excellent Execution: The instruction is implemented flawlessly. Every aspect—object type, placement, orientation, physical interaction (e.g., proper support, no clipping), and semantic context—matches the directive exactly. The result looks like a native part of the original photograph, with no detectable errors in logic, physics, or execution.
'''

AGG_SCORE = """
You are an Image Evaluation Validator responsible for verifying model-generated assessments of edited images. Your task is to review these evaluations based on specific criteria provided in the original evaluation task.

The original evaluation task involves:{task}

You will be given:
- the reference and edited images
- A list of model-generated evaluations, each in the format: <Reason>[...]</Reason><Score>X</Score>.

{prompt}
The following is several evaluations:
{evaluations}

Your validation must follow this three-step process:

1. **Aggregate Claims**: Extract every factual claim, observation, or alleged flaw mentioned across all <Reason> sections.

2. **Verify Against Evidence**: According to the edited image, determine which of these claims are actually true, false, or unsupported. 
The deduction statements regarding wearing patterns and physical laws in each evaluation may not be groundless. Please treat these evaluations with caution and carefully examine them.

3. **Evaluate Each Assessment**: For each original evaluation, check:
- Whether its reasoning relies only on verified facts,
- Whether it correctly applies the rubric definitions,
- Whether its final score logically follows from accurate observations,
- Whether it fails to mention a critical flaw that is both present and relevant to the rubric.

Only if all conditions are met should the evaluation be marked as valid (1). Otherwise, mark it as invalid (0).

Provide your full reasoning in the <Thought> tag. Then output a list of 0s and 1s in the exact order of the input evaluations inside the <Answer> tag. Do not include any extra text, formatting, or punctuation beyond what is required.

Output Format:
<Thought>
[Your step-by-step verification and analysis]
</Thought>
<Answer>[1,0,1,...]</Answer>
"""